.PHONY: clean All

All:
	@echo "----------Building project:[ 1_Hello_World - Debug ]----------"
	@cd "1_Hello_World" && "$(MAKE)" -f  "1_Hello_World.mk"
clean:
	@echo "----------Cleaning project:[ 1_Hello_World - Debug ]----------"
	@cd "1_Hello_World" && "$(MAKE)" -f  "1_Hello_World.mk" clean
